data_root: /data1/nico_arrow_vehicle/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
finetune_mode: coop_finetune
num_workers: 0
backbone_name: ViT-B/32
label_size: 9
learning_rate: 0.002

classname_path: weights/NICO_vehicle.txt
