data_root: /data1/nico_arrow_vehicle/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
finetune_mode: promptless_finetune
num_workers: 0
backbone_name: ViT-B/32
label_size: 9

classname_path: weights/NICO_vehicle.txt
prompt_template: this is
