data_root: /data1/nico_arrow_vehicle/
num_gpus: 1
num_nodes: 1 
per_gpu_batchsize: 64
test_only: True
finetune_mode: prompt_finetune
backbone_name: ViT-B/32
label_size: 9

classname_path: weights/NICO_vehicle.txt
prompt_template: this is
