data_root: /data4/pacs_arrow/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
load_path: weights/vilt_200k_mlm_itm.ckpt
load_path_prompt: weights/vilt_200k_mlm_itm.ckpt 
finetune_mode: prompt_proreg
num_workers: 0
alpha: 0.5
gamma: 0.5
kd_loss: xERM
# test_domain: sketch
# test_domain: cartoon
test_domain: art_painting

classname2idx: weights/bert_to_PACS.txt
prompt_template: this is a [MASK].