data_root: /data4/pacs_arrow/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
finetune_mode: prompt_finetune
backbone_name: ViT-B/32
num_workers: 0
test_domain: sketch
# test_domain: cartoon
# test_domain: art_painting
# test_domain: photo

classname_path: weights/PACS.txt
prompt_template: this is