data_root: /data4/pacs_arrow/
num_gpus: 1
num_nodes: 1 
per_gpu_batchsize: 64
test_only: True
finetune_mode: prompt_finetune
backbone_name: ViT-B/32
test_domain: sketch
# test_domain: cartoon
# test_domain: art_painting
# test_domain: photo
save_result: True

classname_path: weights/PACS.txt
prompt_template: this is
