data_root: /data1/nico_arrow_animal/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
finetune_mode: prompt_proreg
alpha: 0.9 
T: 1
num_workers: 0
backbone_name: ViT-B/32

classname_path: weights/NICO_animal.txt
prompt_template: this is
 
