data_root: /data1/nico_arrow_animal/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
load_path: weights/vilt_200k_mlm_itm.ckpt
load_path_prompt: weights/vilt_200k_mlm_itm.ckpt 
finetune_mode: promptless_proreg
alpha: 0.5
T: 1
num_workers: 0

classname2idx: weights/bert_to_NICO_animal.txt
prompt_template: this animal is [MASK].
question_template: what is the animal?