data_root: /data1/nico_arrow_animal/
num_gpus: 1
num_nodes: 1 
per_gpu_batchsize: 64
test_only: True
finetune_mode: prompt_finetune
backbone_name: ViT-B/32

classname_path: weights/NICO_animal.txt
prompt_template: this is
