data_root: /data1/nico_arrow_animal/
num_gpus: 1
num_nodes: 1 
per_gpu_batchsize: 64
load_path: weights/nico_animal_prompt_finetune.ckpt
finetune_mode: ensemble_test
validate_only: True
T: 1
alpha: 0.1
num_workers: 0
backbone_name: ViT-B/32

classname_path: weights/NICO_animal.txt
prompt_template: this is

