data_root: /data1/nico_arrow/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
load_path: weights/vilt_200k_mlm_itm.ckpt
finetune_mode: promptless_finetune
num_workers: 0
label_size: 19

classname2idx: weights/bert_to_NICO.txt
question_template: what is the object?