data_root: /data1/nico_arrow/
num_gpus: 1
num_nodes: 1 
per_gpu_batchsize: 64
load_path: weights/vilt_200k_mlm_itm.ckpt
test_only: True
finetune_mode: prompt_finetune
label_size: 19

classname2idx: weights/bert_to_NICO.txt
prompt_template: this is [MASK].
