data_root: /data3/DomainNet/
classname_path: /data3/DomainNet/domain_net_classnames.txt

num_gpus: 1
num_nodes: 1 
per_gpu_batchsize: 64
validate_only: True
finetune_mode: prompt_finetune
backbone_name: ViT-B/32
save_result: False

prompt_template: a photo of a
