data_root: /data3/DomainNet/
classname_path: /data3/DomainNet/domain_net_classnames.txt

num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
finetune_mode: prompt_proreg
backbone_name: ViT-B/32
num_workers: 0
alpha: 2
gamma: 1
# T: 2
kd_loss: xERM

prompt_template: a photo of a