data_root: /data1/bar_arrow/bar_arrow_100/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
finetune_mode: prompt_proreg
T: 1
alpha: 0.5
num_workers: 0
backbone_name: ViT-B/32

classname_path: weights/BAR.txt
prompt_template: the man is 
