data_root: /data1/bar_arrow/bar_arrow_100/
num_gpus: 4
num_nodes: 1 
per_gpu_batchsize: 16
load_path: weights/vilt_200k_mlm_itm.ckpt
load_path_prompt: weights/vilt_200k_mlm_itm.ckpt 
finetune_mode: promptless_proreg
T: 1
alpha: 0.5
num_workers: 0

classname2idx: weights/bert_to_BAR.txt
prompt_template: the man is [MASK].
question_template: what is the sport?